### ISSUE TITLE
Getter for `PcSaftParameters` and `PcSaftRecord`

### ISSUE THREAD

**Issue by prehner** [feos-org/feos-pcsaft#13]
Particularly for gc methods it would be useful to access the records from python. In particular:

- getter for `PCSaftParameters.pure_records`
- getter (and potentially setter) for `PCSaftRecord.x`

**Comment by g-bauer** [comment]
I agree that being able to access the entries should be implemented.

Now for setters - do you want to be able to set entries of a record in place inside the `PCSaftParameter` object? I think that would be possible as well as pretty nice for e.g. parameter fits but it would require some changes to the underlying data structure (we could put the records into `RefCell<Rc<...>>`).

**Comment by prehner** [comment]
In this context a getter for the parameters from a `PcSaft` object should also be added.

`feos-core` implements setter for the fields of `PureRecord` etc. which is fine imo. Setter for `PcSaftRecord` would therefore be in line but I don't really see a [use case](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

For `PcSaftParameters` I think we fare best if they are by design immutable and are only created using either of the constructors (that all call the one main constructor). In particular because dependent variables (like `sigma_ij`) are also stored in the parameter set.
