### ISSUE TITLE
GC - How to handle molecules with multiple segments that contain dipole or quadrupole moments? 

### ISSUE THREAD

**Issue by g-bauer** [feos-org/feos-pcsaft#43]
Currently, parameters are constructed using a simple sum of dipole-(DM) and quadrupole moments(QM). 
Sauer et al. only inspected molecules with a *single* fragment with a DM. It is thus not clear how to treat molecules having multiple segments with DM/QM. We should add a warning when molecules are constructed that contain multiple DM/QM to make that clear to users.

**Comment by prehner** [comment]
This is dealt with in the updated `Parameter` trait.
